### ISSUE TITLE
Mag Limit Switch Presentation

### ISSUE THREAD

**Issue by CarlColglazier** [team2059/website#8]
It should be posted somewhere under resources. Perhaps `resources/electrical/___`?

**Comment by AquaMorph** [comment]
Yeah that sounds good.

**Comment by CarlColglazier** [comment]
Completed with #9.

**Comment by JKeeganPierce** [comment]
Middle set of pictures do not load on website.
![screen shot 2015-10-22 at 1 33 37 pm](https://cloud.githubusercontent.com/assets/10499108/10672997/8bdb2b24-78c1-11e5-9552-0ed4005f41b2.png)

**Comment by AquaMorph** [comment]
Fixed. They way the hosting server is set up has case sensitivity for file extensions.
